// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UEHVvvQPcpy_Z9gds2PEi8Ya4YnLsno',
    appId: '1:586841675803:web:97c1ff93ce05778b0940be',
    messagingSenderId: '586841675803',
    projectId: 'cloudfirestore-666ff',
    authDomain: 'cloudfirestore-666ff.firebaseapp.com',
    storageBucket: 'cloudfirestore-666ff.appspot.com',
    measurementId: 'G-PZRHF2VBKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKASr8cLz3-GoEuCDCToONvxO6DZSHWk',
    appId: '1:586841675803:android:58a4b889fd9af2ba0940be',
    messagingSenderId: '586841675803',
    projectId: 'cloudfirestore-666ff',
    storageBucket: 'cloudfirestore-666ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzwjQiUk2X5mZsMOFGQlDZzG5mrBYgdgc',
    appId: '1:586841675803:ios:357742f4e028703a0940be',
    messagingSenderId: '586841675803',
    projectId: 'cloudfirestore-666ff',
    storageBucket: 'cloudfirestore-666ff.appspot.com',
    iosBundleId: 'com.example.firebaseFirestoreNewEf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzwjQiUk2X5mZsMOFGQlDZzG5mrBYgdgc',
    appId: '1:586841675803:ios:56303431cc0d17cb0940be',
    messagingSenderId: '586841675803',
    projectId: 'cloudfirestore-666ff',
    storageBucket: 'cloudfirestore-666ff.appspot.com',
    iosBundleId: 'com.example.firebaseFirestoreNewEf.RunnerTests',
  );
}
